model_config: "configs/autoencoder_vq_f8.yaml"
mode: 0

data_path:  "/disk1/mindone/songyuanwei/datasets/celeba_hq_256/train/"
size: 256
crop_size: 256
flip: True

output_path: "outputs/vae_celeba"

use_discriminator: False
batch_size: 4

epochs: 60
ckpt_save_interval: 1

dtype: "fp32"
init_loss_scale: 1.

scheduler: "constant"
use_ema: False
